/**
 * i18n.js - 国际化配置
 */

// 语言配置
const i18n = {
    zh: {
        // UI 文本
        title: "MAMMALIA",
        subtitle: "哺乳纲演化时间树 · 沉浸式导览",
        enterBtn: "探索演化树",
        loading: "资源加载中...",
        
        // 控制按钮
        btnCollapse: "逐级收起",
        btnExpand: "逐级展开",
        btnInfo: "说明与日志",
        searchPlaceholder: "搜索科名（中文/拉丁名）...",
        noResults: "无匹配结果",
        
        // 彩蛋
        originBtn: "溯源：最后的合弓纲",
        exitEggBtn: "返回现代哺乳纲",
        easterEggText: "我们是合弓纲在这颗星球上，最后的孑遗。",
        
        // 模态框
        aboutTitle: "关于本项目",
        aboutIntro: "这是一个交互式哺乳纲演化可视化项目，旨在以沉浸式的方式展示从合弓纲到现代哺乳动物壮丽的演化历程。",
        dataTitle: "数据与技术说明",
        dataSource: "数据基准",
        dataSourceDesc: "：分类系统与演化关系主要参考最新的 Mammal Diversity Database (MDD) v2.3。",
        timeScale: "时间标尺",
        timeScaleDesc: "：演化树节点时间主要标记为冠群 (Crown Group) 的分化时间。",
        imageGen: "图像生成",
        imageGenDesc: "：本项目囊括了近现代哺乳纲 167个科 的代表物种画像，均由 nanobanana 模型生成。受限于开发者的专业背景，难以完全甄别 AI 在特定物种形态特征上的细微谬误，若发现配图有误，恳请不吝指正。",
        techStack: "技术架构",
        techStackDesc: "：本项目基于 D3.js (2D) 与 Three.js (3D) 混合开发。为了提升国内访问体验，所有图像资源均采用 CDN 链路进行加速分发。",
        guideTitle: "操作指南",
        guideDrag: "拖拽画布",
        guideDragDesc: "：自由移动演化树视图",
        guideZoom: "滚轮/双指",
        guideZoomDesc: "：缩放查看演化细节",
        guideNode: "点击节点",
        guideNodeDesc: "：展开或收起演化分支",
        guideText: "点击文字",
        guideTextDesc: "：查看物种/科目的详细资料卡片",
        thanksTitle: "致谢与联系",
        thanksGemini: "本项目在开发过程中特别感谢 Google Gemini 提供的代码协助与技术支持。",
        thanksNote: "这不仅是一个科普项目，也是一次对生命演化史的致敬。受限于个人知识水平，项目中可能存在数据错误或Bug，您的每一个反馈都是项目进步的动力。",
        version: "当前版本",
        feedback: "反馈邮箱",
        closeBtn: "×"
    },
    en: {
        // UI 文本
        title: "MAMMALIA",
        subtitle: "Mammalian Evolution Tree · Immersive Guide",
        enterBtn: "Explore Evolution",
        loading: "Loading Resources...",
        
        // 控制按钮
        btnCollapse: "Collapse Level",
        btnExpand: "Expand Level",
        btnInfo: "About & Changelog",
        searchPlaceholder: "Search family (Chinese/Latin)...",
        noResults: "No Results",
        
        // 彩蛋
        originBtn: "Origin: Last Synapsids",
        exitEggBtn: "Return to Modern Mammals",
        easterEggText: "We are the last remnants of Synapsida on this planet.",
        
        // 模态框
        aboutTitle: "About This Project",
        aboutIntro: "This is an interactive visualization project of mammalian evolution, designed to present the magnificent evolutionary journey from Synapsids to modern mammals in an immersive way.",
        dataTitle: "Data & Technical Notes",
        dataSource: "Data Source",
        dataSourceDesc: ": The taxonomy and evolutionary relationships are primarily based on the latest Mammal Diversity Database (MDD) v2.3.",
        timeScale: "Time Scale",
        timeScaleDesc: ": The divergence times of tree nodes are mainly marked as Crown Group divergence times.",
        imageGen: "Image Generation",
        imageGenDesc: ": This project includes representative species illustrations of 167 families of modern mammals, all generated by the nanobanana AI model. Due to the developer's limited expertise, it's difficult to fully verify AI-generated anatomical details. Please feel free to point out any errors.",
        techStack: "Technical Architecture",
        techStackDesc: ": This project is developed using a hybrid of D3.js (2D) and Three.js (3D). To improve access experience, all image resources are distributed via CDN.",
        guideTitle: "User Guide",
        guideDrag: "Drag Canvas",
        guideDragDesc: ": Freely move the evolution tree view",
        guideZoom: "Scroll/Pinch",
        guideZoomDesc: ": Zoom to view evolutionary details",
        guideNode: "Click Node",
        guideNodeDesc: ": Expand or collapse evolutionary branches",
        guideText: "Click Text",
        guideTextDesc: ": View detailed information cards of species/families",
        thanksTitle: "Acknowledgments & Contact",
        thanksGemini: "Special thanks to Google Gemini for code assistance and technical support during development.",
        thanksNote: "This is not only a science education project, but also a tribute to the history of life evolution. Due to limited personal knowledge, there may be data errors or bugs in the project. Your feedback is the driving force for project improvement.",
        version: "Current Version",
        feedback: "Feedback Email",
        closeBtn: "×"
    }
};

// 当前语言状态
let currentLanguage = 'zh';

/**
 * 切换语言
 * @param {string} lang - 语言代码 ('zh' 或 'en')
 */
function switchLanguage(lang) {
    if (!i18n[lang]) {
        console.warn(`Language '${lang}' not found, keeping current language`);
        return;
    }
    currentLanguage = lang;
    updateUILanguage();
}

/**
 * 获取翻译文本
 * @param {string} key - 翻译键（支持点号分隔的路径）
 * @returns {string} 翻译后的文本
 */
function t(key) {
    const keys = key.split('.');
    let value = i18n[currentLanguage];
    
    for (const k of keys) {
        value = value?.[k];
    }
    
    return value || key;
}

/**
 * 更新 UI 语言
 */
function updateUILanguage() {
    // 更新标题和副标题
    const title = document.querySelector('h1');
    const subtitle = document.querySelector('.subtitle');
    const enterBtn = document.getElementById('enter-btn');
    
    if (title) title.textContent = t('title');
    if (subtitle) subtitle.textContent = t('subtitle');
    if (enterBtn) enterBtn.textContent = t('enterBtn');
    
    // 更新加载文本
    const loading = document.getElementById('loading-screen');
    if (loading) loading.textContent = t('loading');
    
    // 更新控制按钮
    const btnCollapse = document.getElementById('btn-collapse-all');
    const btnExpand = document.getElementById('btn-expand-all');
    const btnInfo = document.getElementById('btn-info');
    
    if (btnCollapse) btnCollapse.title = t('btnCollapse');
    if (btnExpand) btnExpand.title = t('btnExpand');
    if (btnInfo) btnInfo.title = t('btnInfo');
    
    // 更新搜索框
    const searchInput = document.getElementById('search-input');
    if (searchInput) searchInput.placeholder = t('searchPlaceholder');
    
    // 更新彩蛋按钮
    const originBtn = document.getElementById('origin-btn');
    const exitEggBtn = document.getElementById('exit-egg-btn');
    const easterEggText = document.querySelector('.ee-text-main');
    
    if (originBtn) originBtn.textContent = t('originBtn');
    if (exitEggBtn) exitEggBtn.textContent = t('exitEggBtn');
    if (easterEggText) easterEggText.textContent = t('easterEggText');
    
    // 更新模态框内容
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translation = t(key);
        if (translation && translation !== key) {
            el.textContent = translation;
        }
    });
}

/**
 * 获取当前语言
 * @returns {string} 当前语言代码
 */
function getCurrentLanguage() {
    return currentLanguage;
}

/**
 * 获取多语言文本 - 用于数据字段
 * @param {object} data - 数据对象
 * @param {string} field - 字段名（如 'name', 'description'）
 * @returns {string} 对应语言的文本
 */
function getLocalizedText(data, field) {
    const lang = currentLanguage;
    
    if (field === 'name') {
        // 名称字段
        if (lang === 'en') {
            // 英文模式：优先显示英文名称，如果没有则显示拉丁学名
            if (data.en_name) {
                return data.en_name;
            } else if (data.family_en) {
                return data.family_en;
            } else if (data.en_name || data.family_en) {
                return data.en_name || data.family_en;
            } else {
                // 如果都没有，显示拉丁学名（通常是键名）
                return data.cn_name || data.family_cn || 'Unknown';
            }
        } else {
            // 中文模式
            return data.cn_name || data.family_cn || data.en_name || data.family_en || '未命名';
        }
    } else if (field === 'description') {
        // 描述字段
        if (lang === 'en') {
            // 英文模式：如果有英文描述就用，否则显示简化信息
            if (data.en_description) {
                return data.en_description;
            } else if (data.family_en || data.en_name) {
                const name = data.family_en || data.en_name;
                return `${name} - A family/clade of mammals. (Detailed description available in Chinese only)`;
            } else {
                return 'Description not available in English.';
            }
        } else {
            // 中文模式
            return data.description || data.desc || '暂无详细资料...';
        }
    }
    
    return '';
}
